print()
print("\033[92mProject successfully created!!\033[0m")
print("\033[93m")
print("`7MMF\'  `7MMF\'      db      `7MM\"\"\"Mq.`7MM\"\"\"Mq.`YMM\'   `MM\'     ")
print("  MM      MM       ;MM:       MM   `MM. MM   `MM. VMA   ,V       ")
print("  MM      MM      ,V^MM.      MM   ,M9  MM   ,M9   VMA ,V        ")
print("  MMmmmmmmMM     ,M  `MM      MMmmdM9   MMmmdM9     VMMP         ")
print("  MM      MM     AbmmmqMA     MM        MM           MM          ")
print("  MM      MM    A\'     VML    MM        MM           MM          ")
print(".JMML.  .JMML..AMA.   .AMMA..JMML.    .JMML.       .JMML.        ")
print("                                                                 ")
print("  .g8\"\"\"bgd   .g8\"\"8q. `7MM\"\"\"Yb. `7MMF\'`7MN.   `7MF\' .g8\"\"\"bgd  ")
print(".dP\'     `M .dP\'    `YM. MM    `Yb. MM    MMN.    M .dP\'     `M  ")
print("dM\'       ` dM\'      `MM MM     `Mb MM    M YMb   M dM\'       `  ")
print("MM          MM        MM MM      MM MM    M  `MN. M MM           ")
print("MM.         MM.      ,MP MM     ,MP MM    M   `MM.M MM.    `7MMF\'")
print("`Mb.     ,\' `Mb.    ,dP\' MM    ,dP\' MM    M     YMM `Mb.     MM  ")
print("  `\"bmmmd\'    `\"bmmd\"\' .JMMmmmdP\' .JMML..JML.    YM   `\"bmmmdPY  ")
print("\033[0m")
pass